# preload = /home/wilt/ALL/Wallpapers/Linux/anon.jpg
# wallpaper = , /home/wilt/ALL/Wallpapers/Linux/anon.jpg

wallpaper {
    monitor = 
    # path = ~/ALL/Wallpapers/Linux/anon.jpg
    path = ~/ALL/Wallpapers/Linux/Linux-Nixos-operating-system-minimalism-2175179-wallhere.com.jpg
    fit_mode = cover
}

# path = /home/wilt/ALL/Wallpapers/Linux/anon.jpg

splash = false
